---
title: "Modelos de lengua para clasificación y traducción automática"
---

Fecha de la sesión: {{< var fechas.teoria.s4 >}}

Una de las reglas básicas a la hora de resolver problemas en el PLN es entender que no siempre es necesario usar modelos gigantescos para resolver ciertas tareas. Es cierto que los LLM tienen la interesante propiedad de poder afrontar tareas de clasificación de texto sin necesidad de ser entrenados específicamente para ello. Así, podemos instruirle mediante *few-shot learning* para que identifiquen el sentimiento o el tema de un texto, clasifiquen los nombres propios, o determinen las premisas y conclusiones de un argumento. Sin embargo, en muchas ocasiones podemos resolver este tipo de problemas usando una red neuronal más sencilla para obtener representaciones vectoriales de los textos y entrenando un clasificador sencillo sobre estas representaciones. Estos modelos también se denominan *modelos de lengua*, aunque para distinguirlos de los LLMs se suelen denominar *modelos de lengua enmascarados* (*masked language models*, en inglés), basándonos en la forma en que se suelen preentrenar. 

Por otro lado, la traducción automática es una de las tareas más exploradas en el PLN. Ya finales de los años 40 del siglo pasado, cuando los primeros computadores electrónicos acababan de aparecer, se planteó la posibilidad de usarlos para traducir textos de un idioma a otro. Aunque en la siguiente década se desarrollaron los primeros sistemas de traducción automática, no fue hasta la llegada de los modelos neuronales hacia finales de la segunda década del siglo XXI cuando la traducción automática entre lenguas con interés comercial y elevada disponibilidad de datos comenzó a tener la calidad suficiente como para no necesitar la corrección humana. No obstante, pese a estos avances, la traducción automática sigue siendo un reto en dominios como el literario o para miles de lenguas del mundo que no tienen la disponibilidad de datos suficiente para entrenar modelos de IA. La traducción automática puede abordarse con LLMs, pero también con modelos específicos más eficientes entrenados específicamente para esta tarea. 

En esta sesión, estudiaremos tanto los modelos de lengua para clasificación como la traducción automática.

Recuerda que esta asignatura sigue una metodología de clase invertida, por lo que antes de la sesión de teoría debes estudiar los materiales que se indican a continuación y realizar las actividades que se proponen. El tiempo medio estimado para el estudio es de unas 4 horas, aunque puede variar según tu nivel de conocimientos previos y tu experiencia en el estudio de este tipo de contenidos.

## Materiales a estudiar antes de la sesión del {{< var fechas.teoria.s4 >}} 

El contenido de esta sesión lo puedes encontrar en los siguientes apartados del [libro]({{< var jurafsky.url >}}) de Jurafsky y Martin:

::: {.tabla-80}

|Capítulo|Apartados o páginas|Contenido|
|---|---|---|
|Masked language models [§9]({{< var jurafsky.url >}}/9.pdf)|capítulo completo|Codificadores bidireccionales, preentrenamiento y ajuste de modelos de lengua enmascarados|
|Machine translation [§10]({{< var jurafsky.url >}}/10.pdf)|capítulo completo|Lenguas del mundo, arquitectura codificador-descodificador, beam-search, evaluación|

:::

## Actividades previas a la sesión del {{< var fechas.teoria.s4 >}}

Una vez hayas estudiado los materiales, realiza el test que puedes encontrar en el [Moodle de la asignatura]({{< var moodle.url >}}).

El plazo para realizar las actividades previas finaliza el día anterior a la sesión de teoría.

## Evaluación asistida por un tutor inteligente

Usa el siguiente prompt para evaluar tu comprensión de los conceptos fundamentales de esta sesión con ayuda de tu chat o agente de inteligencia artificial favorito.

<div style="border: 1px solid #888; font-size: 0.9em; padding: 1em;">

{{< include _socratic.md >}}

1. ¿Por qué puede interesar entrenar un modelo de lengua enmascarado y no un modelo de lengua causal?
2. ¿Cuáles son las diferencias a nivel de arquitectura y de la forma de trabajar con la secuencia de entrada entre un modelo de lengua enmascarado y un modelo de lengua causal?
3. ¿Cómo se usan máscaras a la entrada de un modelo preentrenado y cuál es su objetivo?
4. ¿Por qué se considera adicionalmente en ciertas ocasiones la tarea de predicción de la siguiente frase en el preentrenamiento de un modelo de lengua enmascarado?
5. ¿Cómo se aplica un clasificador basado en codificador bidireccional a una tarea de detección de entidades nombradas?
6. ¿Con qué arquitecturas basadas en el transformer se puede abordar la traducción automática y cuáles son sus diferencias?
7. ¿Por qué se usa la búsqueda por haz (*beam search*) en la descodificación de un modelo de traducción automática y no se usa la predicción de la palabra más probable en cada paso o se muestrea la distribución de probabilidad de la siguiente palabra?
8. ¿Por qué existen métricas neuronales y no neuronales para evaluar la calidad de la traducción automática y cuáles son sus diferencias?

</div>


## Contenidos de la sesión 

En la sesión de teoría presencial repasaremos los conceptos más complejos del tema y resolveremos las dudas que hayan surgido durante su estudio.