---
title: "Palabras, tokens y embeddings incontextuales"
---

Fecha de la sesión: {{< var fechas.teoria.s2 >}}

Las redes neuronales que procesan texto son básicamente secuencias de operaciones matemáticas sobre tensores de números. Por ello, el primer paso para que una red neuronal pueda recibir texto a la entrada es convertir las palabras en vectores de números. En esta sesión veremos cómo realizar esta conversión mediante un algoritmo *clásico* basado en cuentas de palabras y mediante un algoritmo neuronal que aprende a representar las palabras en un espacio vectorial como resultado indirecto de entrenar la red para una tarea de clasificación de palabras. Además, como paso previo, estudiarás por qué en procesamiento del lenguaje natural no se suele trabajar con palabras, sino con *tokens*, y cómo se implementa un *tokenizador* que transforma un texto en una secuencia de tokens.

Recuerda que esta asignatura sigue una metodología de clase invertida, por lo que antes de la sesión de teoría debes estudiar los materiales que se indican a continuación y realizar las actividades que se proponen. El tiempo medio estimado para el estudio es de unas 3 horas, aunque puede variar según tu nivel de conocimientos previos y tu experiencia en el estudio de este tipo de contenidos.

## Materiales a estudiar antes de la sesión del {{< var fechas.teoria.s2 >}} 

El contenido de esta sesión lo puedes encontrar en los siguientes apartados del [libro]({{< var jurafsky.url >}}) de Jurafsky y Martin:

::: {.tabla-80}

|Capítulo|Apartados o páginas|Contenido|
|---|---|---|
|words and tokens [§2]({{< var jurafsky.url >}}/2.pdf)|2.1 y 2.4|Palabras, tokens y tokenizadores|
|embeddings [§5]({{< var jurafsky.url >}}/5.pdf)|5.1 a 5.5, 5.8|Embeddings incontextuales neuronales y basados en cuentas|

:::

## Actividades previas a la sesión del {{< var fechas.teoria.s2 >}}

Una vez hayas estudiado los materiales, realiza el test que puedes encontrar en el [Moodle de la asignatura]({{< var moodle.url >}}).

El plazo para realizar las actividades previas finaliza el día anterior a la sesión de teoría.

## Evaluación asistida por un tutor inteligente

Usa el siguiente prompt para evaluar tu comprensión de los conceptos fundamentales de esta sesión con ayuda de tu chat o agente de inteligencia artificial favorito.

<div style="border: 1px solid #888; font-size: 0.9em; padding: 1em;">

{{< include _socratic.md >}}

1. ¿Qué elementos comparte el algoritmo de skip-gram con el entrenamiento de un regresor logístico?
2. ...

</div>


## Contenidos de la sesión 

