---
title: "Transformers y preentrenamiento de modelos de lengua"
---

Fecha de la sesión: {{< var fechas.teoria.s3 >}}

Un modelo de lengua es básicamente un sistema que dado un prefijo de texto, predice las probabilidades que tienen las palabas de un conjunto llamado *vocabulario* de ser la siguiente palabra del texto. Los modelos de lengua no son una invención reciente. Su origen se puede situar décadas antes de la llegada de los computadores electrónicos, cuando en los primeros años del siglo XX Andréi Márkov modeló los caracteres de un texto como un proceso estocástico. Claude Shannon a finales de los años 40 perfeccionó la formalización de las ideas de Markov usando el concepto de *n*-grama (modelos probabilísticos en los que la probabilidad de una palabra depende de las *n-1* palabras anteriores) para estimar la entropía de la lengua inglesa. Ya en el siglo XXI con el auge del aprendizaje profundo los modelos de lengua basados en redes neuronales se consolidan como la alternativa más potente para modelar el lenguaje natural. Aunque ya existían modelos de lengua neuronales mucho antes de la llegada de la arquitectura transformer, es esta arquitectura la que más ha contribuido al entrenamiento masivo y popularización de los modelos de lengua en los llamados *modelos de lengua masivos* (LLMs, por el inglés, *large language models*). En esta sesión, repasarás los elementos fundamentales del transformer y estudiarás cómo se entrenan y usan los LLMs.

Recuerda que esta asignatura sigue una metodología de clase invertida, por lo que antes de la sesión de teoría debes estudiar los materiales que se indican a continuación y realizar las actividades que se proponen. El tiempo medio estimado para el estudio es de unas 3 horas, aunque puede variar según tu nivel de conocimientos previos y tu experiencia en el estudio de este tipo de contenidos.

## Materiales a estudiar antes de la sesión del {{< var fechas.teoria.s3 >}} 

El contenido de esta sesión lo puedes encontrar en los siguientes apartados del [libro]({{< var jurafsky.url >}}) de Jurafsky y Martin:

::: {.tabla-80}

|Capítulo|Apartados o páginas|Contenido|
|---|---|---|
|Transformers and pretraining [§7]({{< var jurafsky.url >}}/7.pdf)|capítulo completo|Mecanismo de atención, bloques de un transformer, descodificación|

:::

## Actividades previas a la sesión del {{< var fechas.teoria.s3 >}}

Una vez hayas estudiado los materiales, realiza el test que puedes encontrar en el [Moodle de la asignatura]({{< var moodle.url >}}).

El plazo para realizar las actividades previas finaliza el día anterior a la sesión de teoría.

## Evaluación asistida por un tutor inteligente

Usa el siguiente prompt para evaluar tu comprensión de los conceptos fundamentales de esta sesión con ayuda de tu chat o agente de inteligencia artificial favorito.

<div style="border: 1px solid #888; font-size: 0.9em; padding: 1em;">

{{< include _socratic.md >}}


1. ¿Por qué el mecanismo de atención se calcula de la forma que se calcula en un transformer y no de otras formas?
2. ¿Qué efecto tiene en estrategias de descodificación como *top-k$ o *top-p* el valor del parámetro correspondiente (*k* o *p*)? ¿Y el valor de la temperatura?
3. ¿Puede el contexto de un transformer ser indefinidamente largo? ¿Qué elementos influyen en ello?
4. ¿Cuál es el propósito de la normalización de capa?
5. ¿Cuál es el propósito de los embeddings posicionales?
6. ¿Qué papel juega el flujo residual (*residual stream*) en el entrenamiento y en la inferencia de un transformer?

</div>


## Contenidos de la sesión 

En la sesión de teoría presencial repasaremos los conceptos más complejos del tema y resolveremos las dudas que hayan surgido durante su estudio.